### ISSUE TITLE
Remote streams not working

### ISSUE THREAD

**Issue by HelloRibs** [hydra-synth/hydra#186]
pb.list() returns a ['[object Object]']

**Comment by ritchse** [comment]
Further investigation:
Setting a two way stream (with custom names set to each peer). The source doesn't load anything. Matter of fact. `s0.src` returns null.
Running `s0.initStream('name')` logs:
```
Already connected to.. undefined
```
Seems Hydra can't find any other instances of Hydra running on the same server.

**Comment by HelloRibs** [comment]
Hi! I'm looking at the streaming issue and found some potential errors:
- The user _nick_ is never saved in the id/nicks object, or at least I didn't find it
- The Socket instance appears as `{ connected: false, ... }` and it does not look like it's sending anything
- I hardcoded the id/nicks and it actually showed the `console.log("THIS IS THE PEER", peer)` and `console.log("peer signal sending over sockets", id, signal)` apparently with good data, but
- The streaming never started

I was wondering if this issue could come from the _socket.io_ and _socket.io-client_ package versions. I'm just getting familiar with the code and hoping this information to be helpful 🌹

**Comment by ojack** [comment]
Yes! It seems that it is never establishing a connection to the server.
Good idea to check socket.io

**Comment by HelloRibs** [comment]
Small update on this: I tried moving to older commits but I got the same `['[object Object]']` when `pb.list()`

**Comment by ojack** [comment]
@HelloRibs that fixed it! reverted the socket.io versions and now all fixed in v1.3.4 :) :)

**Comment by milangress** [comment]
@ojack hey it think the patchbay / connection to other streams broke again :( pb.list() returns a `['[object Object]']`

do you think it would be possible to take a look again? I would love to use it in a workshop
