### ISSUE TITLE
update readme/submodules to https

### ISSUE THREAD

**Issue by micuat** [hydra-synth/hydra#198]
currently they are pointing to git@github.com:hydra-synth/hydra.git etc - which only works if you have write permission (?). I think they should be updated to https:// instead so everyone can download the project

**Comment by ojack** [comment]
I think this would cause problems for ppl using git via ssh (explanation here: https://www.damirscorner.com/blog/posts/20210423-ChangingUrlsOfGitSubmodules.html)
I am going to try using relative URLs instead.

**Comment by ojack** [comment]
Fixed https://github.com/hydra-synth/hydra/commit/1839b279b8dfb349a74f92bf373ccff30e34d984
