### ISSUE TITLE
Adjusting speed using midi controller

### ISSUE THREAD

**Issue by staus** [hydra-synth/hydra#207]
I love the speed function, but it seems like it doesn't work to connect it to a controller. Unless I'm doing something wrong? The scene just stops rendering as soon as I try.
Would be super powerful if it did, though!

```js
speed = cc(0).range(-5, 5)
```

**Comment by ritchse** [comment]
`speed` is not a function, is a variable. So you would have to periodically change for it to act reactively. If `cc(0).range(-5, 5)` returns a Number value, you could try setting speed at every frame using the `update` function (which runs every frame):

```js
update = (dt) => {
    speed = cc(0).range(-5, 5)
}
```

However I imagine `cc(0).range(-5, 5)` doesn't return a value given the behavior you described. Whatever MIDI library you're using, check if you want get a number value from it.

**Comment by micuat** [comment]
@ritchse thanks, I think this is the way to go. closing...
