### ISSUE TITLE
memory leak / server crash

### ISSUE THREAD

**Issue by ojack** [hydra-synth/hydra#254]
Currently, https://hydra.ojack.xyz/ is crashing repeatedly.

Current server configuration:
- Ubuntu + nginx running on a digital ocean droplet
- pm2 as process manager running the code contained in this repo

**Comment by emptyflash** [comment]
Might make sense to separate the static frontend server and the sketch upload/WebRTC stuff.

**Comment by rseymour** [comment]
This is an idea w/o follow through, but you could _maybe_ look into trying deno as the node runtime? Might be a non-starter, but perhaps: https://deno.com/runtime

I may experiment.

**Comment by emptyflash** [comment]
@ojack also might not be a bad idea to add a CDN in front of the static stuff at some point to reduce the load on the server. Should probably ignore `code` and `sketch_id` query params.

On a related note, looks like the cert and custom sketch loading are broken with the new current setup, but it loads very fast.

**Comment by ojack** [comment]
What cert? Right now there is just a backup static site hosted on github :)


 but actually it could make sense to keep it that way, but be able to talk
to backend for webrtc and gallery

**Comment by ojack** [comment]
Okay, this has been addressed. This repo now contains just the editor, while the backend is at: https://github.com/hydra-synth/hydra-server

And the frontend is hosted on github at: https://github.com/hydra-synth/hydra-synth.github.io
